# Generated by Django 6.0.3 on 2026-03-26 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('google_oauth_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'libraries',
            },
        ),
        migrations.CreateModel(
            name='SongForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('pop', 'Pop'), ('hiphop', 'Hip-Hop'), ('rock', 'Rock'), ('reggae', 'Reggae'), ('country', 'Country'), ('rnb', 'R&B'), ('edm', 'EDM')], max_length=20)),
                ('voice_type', models.CharField(max_length=100)),
                ('mood', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('quota', models.IntegerField(default=20)),
            ],
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
            ],
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed')], default='in_progress', max_length=20)),
                ('song_link', models.URLField(blank=True, help_text='Auto-set after successful AI generation. Never entered by user.', null=True, unique=True)),
                ('created_by', models.CharField(help_text='Name of the Creator who generated this song', max_length=150)),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('cover_image', models.URLField(blank=True, help_text='Optional cover image URL [0..1]', null=True)),
                ('library', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='core.library')),
                ('song_form', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='song', to='core.songform')),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.AddField(
            model_name='songform',
            name='creator',
            field=models.ForeignKey(help_text='Auto-assigned when user becomes a Creator on first submission', on_delete=django.db.models.deletion.CASCADE, related_name='song_forms', to='core.creator'),
        ),
        migrations.AddField(
            model_name='library',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='core.creator'),
        ),
    ]
