# Generated by Django 6.0.3 on 2026-04-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
