# Generated by Django 6.0.3 on 2026-04-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_song_is_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='error_message',
            field=models.TextField(blank=True, help_text='Set if generation fails', null=True),
        ),
    ]
