# Generated by Django 6.0.3 on 2026-03-23 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        ('song_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed')], default='in_progress', max_length=20)),
                ('song_link', models.URLField(blank=True, help_text='Public share/stream link (Cloud Storage URL)', null=True, unique=True)),
                ('created_by', models.CharField(help_text='Name of the Creator who generated this song', max_length=150)),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('cover_image', models.URLField(blank=True, help_text='Cloud Storage URL; optional [0..1]', null=True)),
                ('library', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='library.library')),
                ('song_form', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='song', to='song_form.songform')),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
    ]
