# Generated by Django 6.0.3 on 2026-03-23 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('pop', 'Pop'), ('hiphop', 'Hip-Hop'), ('rock', 'Rock'), ('reggae', 'Reggae'), ('country', 'Country'), ('rnb', 'R&B'), ('edm', 'EDM')], max_length=20)),
                ('voice_type', models.CharField(max_length=100)),
                ('mood', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True, default='')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_forms', to='creator.creator')),
            ],
        ),
    ]
